apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: php-app
  template:
    metadata:
      labels:
        app: php-app
    spec:
      containers:
        - name: php-app
          image: bakill3/php-devops-app:latest  # Replace with your Docker Hub username and image name
          imagePullPolicy: Always               # Ensures the image is always pulled
          ports:
            - containerPort: 80
          env:
            - name: DB_HOST
              value: postgres-service
            - name: DB_USER
              value: myuser
            - name: DB_PASSWORD
              value: mysecretpassword
            - name: DB_NAME
              value: mydatabase
