name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: myuser
          POSTGRES_PASSWORD: mysecretpassword
          POSTGRES_DB: mydatabase
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U myuser -d mydatabase"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: pdo_pgsql

      - name: Clear Composer Cache
        run: composer clear-cache

      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-progress

      - name: Regenerate Composer Autoloader
        run: composer dump-autoload --optimize

      - name: Set execute permissions for PHPUnit
        run: chmod +x vendor/bin/phpunit

      - name: Run PHPUnit tests
        run: vendor/bin/phpunit tests
